### ISSUE TITLE
Tests fail under Python 3.8

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.contenttype#7]
From https://github.com/zopefoundation/zopetoolkit/issues/37:

```
Failure in test test_add_one_file (zope.contenttype.tests.testContentTypes.ContentTypesTestCase)
Traceback (most recent call last):
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 671, in run
    self._callTestMethod(testMethod)
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 628, in _callTestMethod
    method()
  File "/home/mg/src/zopefoundation/zope.contenttype/.tox/py38/lib/python3.8/site-packages/zope/contenttype/tests/testContentTypes.py", line 73, in test_add_one_file
    self._check_types_count(1)
  File "/home/mg/src/zopefoundation/zope.contenttype/.tox/py38/lib/python3.8/site-packages/zope/contenttype/tests/testContentTypes.py", line 33, in _check_types_count
    self.assertEqual(len(mimetypes.types_map),
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 907, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 900, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 572 != 573



Failure in test test_add_two_files (zope.contenttype.tests.testContentTypes.ContentTypesTestCase)
Traceback (most recent call last):
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 671, in run
    self._callTestMethod(testMethod)
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 628, in _callTestMethod
    method()
  File "/home/mg/src/zopefoundation/zope.contenttype/.tox/py38/lib/python3.8/site-packages/zope/contenttype/tests/testContentTypes.py", line 87, in test_add_two_files
    self._check_types_count(2)
  File "/home/mg/src/zopefoundation/zope.contenttype/.tox/py38/lib/python3.8/site-packages/zope/contenttype/tests/testContentTypes.py", line 33, in _check_types_count
    self.assertEqual(len(mimetypes.types_map),
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 907, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/mg/opt/python38/lib/python3.8/unittest/case.py", line 900, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 573 != 575
```

The test passes under Python 3.7.  The diff in Lib/mimetypes.py between 3.7 and 3.8 seems inconsequential.

I would like to know what ContentTypesTestCase.setUp/tearDown thinks it's doing with the `mimetypes.__dict__` manipulations that only do shallow copies of mutable internal data structures?

**Comment by mgedmin** [comment]
On 3.8 `mimetypes.types_map is self._old_state['types_map']`.  On 3.7 they're different objects somehow.

**Comment by mgedmin** [comment]
Ah, I should compare 3.7 from my distro, not 3.7 from latest upstream commit in that branch.

mimetypes.init() used to create a new MimeTypes() instance on every call, but now it re-initializes the same instance.

Upstream commit:
- https://github.com/python/cpython/commit/25fbe33b92cd938e809839feaa3fda97e6ad0980
- https://github.com/python/cpython/commit/2a99fd911ebeecedbb250a05667cd46eca4735b9 (backport into 3.7 branch)

**Comment by mgedmin** [comment]
copy.deepcopy() is not the bandaid we're looking for.
